# Brincando com Pandas

In [92]:
%matplotlib inline

import pandas as pd
import matplotlib.pyplot as plt

In [93]:
data = pd.read_csv('/home/lsp/dados/am/eleicoes_2006_a_2010.csv')
data[:3]

,ano,sequencial_candidato,nome,uf,partido,quantidade_doacoes,quantidade_doadores,total_receita,media_receita,recursos_de_outros_candidatos/comites,...,quantidade_despesas,quantidade_fornecedores,total_despesa,media_despesa,cargo,sexo,grau,estado_civil,ocupacao,votos
0,2006,10001,JOSÉ LUIZ NOGUEIRA DE SOUSA,AP,PT,6,6,16600.0,2766.666667,NaN,...,14,14,16583.60,1184.542857,DEPUTADO FEDERAL,MASCULINO,ENSINO MÉDIO COMPLETO,CASADO(A),VEREADOR,8579
1,2006,10002,LOIVA DE OLIVEIRA,RO,PT,13,13,22826.0,1755.846154,6625.0,...,24,23,20325.99,883.738696,DEPUTADO FEDERAL,FEMININO,SUPERIOR COMPLETO,SOLTEIRO(A),SERVIDOR PÚBLICO ESTADUAL,2757
2,2006,10002,MARIA DALVA DE SOUZA FIGUEIREDO,AP,PT,17,16,148120.8,9257.550000,2250.0,...,123,108,146011.70,1351.960185,DEPUTADO FEDERAL,FEMININO,SUPERIOR COMPLETO,VIÚVO(A),PEDAGOGO,17428

É possível configurar a forma de ler um arquivo, como em:

`file = pd.read_csv('file.csv', sep=';', encoding='latin1', parse_dates=['Date'], dayfirst=True, index_col='Date')`

Mudando o separador para **;**
O encoding para **latin1**
E configurando o formato da data

### Pausa para algumas dicas:

Verificando o tipo do objeto e os métodos e atributos disponíveis

In [94]:
type(data)
dir(data)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__unicode__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_apply_broadcast',
 '_apply_empty_result',
 '_apply_raw',
 '_apply_standard',
 '_at',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_scalar',
 '_combine_const',
 '_combine_frame',
 '_combine_match_columns',
 '_combine_match_index',
 '_combine_series',
 '_combine_series_infer',
 '_compare_frame',
 '_compare_frame_evaluate',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_for_slice',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_dir_additions',
 '_dir_deletions',
 '_ensure_valid_index',
 '_expand_axes',
 '_flex_compare_frame',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_numeric_data',
 '_get_values',
 '_getitem_array',
 '_getitem_column',
 '_getitem_frame',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_iat',
 '_iget_item_cache',
 '_iloc',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_dict',
 '_init_mgr',
 '_init_ndarray',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_loc',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_axis',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_frame_compat',
 '_unpickle_matrix_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'ano',
 'any',
 'append',
 'apply',
 'applymap',
 'as_blocks',
 'as_matrix',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'axes',
 'between_time',
 'bfill',
 'blocks',
 'bool',
 'boxplot',
 'cargo',
 'clip',
 'clip_lower',
 'clip_upper',
 'columns',
 'combine',
 'combine_first',
 'compound',
 'consolidate',
 'convert_objects',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'estado_civil',
 'eval',
 'ewm',
 'expanding',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_csv',
 'from_dict',
 'from_items',
 'from_records',
 'ftypes',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_value',
 'get_values',
 'grau',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'info',
 'insert',
 'interpolate',
 'is_copy',
 'isin',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'ix',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'media_despesa',
 'media_receita',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'nome',
 'notnull',
 'nsmallest',
 'nunique',
 'ocupacao',
 'partido',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantidade_despesas',
 'quantidade_doacoes',
 'quantidade_doadores',
 'quantidade_fornecedores',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'recursos_de_pessoas_fisicas',
 'recursos_de_pessoas_juridicas',
 'recursos_proprios',
 'reindex',
 'reindex_axis',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select',
 'select_dtypes',
 'sem',
 'sequencial_candidato',
 'set_axis',
 'set_index',
 'set_value',
 'sexo',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'sortlevel',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_msgpack',
 'to_panel',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sparse',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'total_despesa',
 'total_receita',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'uf',
 'unstack',
 'update',
 'values',
 'var',
 'votos',
 'where',
 'xs']

Obter ajuda em um notebook

In [95]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.

Ver a lista de funções mágicas do notebook

In [96]:
%quickref

# Voltando

### Selecionando colunas

In [97]:
data[['nome', 'votos']]

                                  nome   votos
0          JOSÉ LUIZ NOGUEIRA DE SOUSA    8579
1                    LOIVA DE OLIVEIRA    2757
2      MARIA DALVA DE SOUZA FIGUEIREDO   17428
3                       ROMALDO MILANI    1193
4               ANSELMO DE JESUS ABREU   29401
5       JOSÉ RODRIGUES DOS SANTOS NETO    1822
6                  JOSÉ TOMAZ DA SILVA     317
7             LUIZ CARLOS MUNHOZ MEIRA    2591
8                  EDILSON VEIRA ROCHA    2551
9        EDUARDO VALVERDE ARAÚJO ALVES   34631
10                    IRINEU RODRIGUES   26856
11            TARCISIO JOÃO ZIMERMMANN  106659
12               WILLIAN GOMES EUGENIO    1859
13            AMAURI GUEDES DE FREITAS    3752
14                  ELIAS RAMOS SOARES    8346
15       FRANCISCO ALVES DA CRUZ FILHO    4621
16          GILBERTO JOSÉ SPIER VARGAS  124686
17                 GLAYDSTON LIRA GOES     609
18                   ISAAC SILVA GOMES      88
19                 IVETE MARIA RIBEIRO    4959
20         PAULO HENRIQUE COSTA MATTOS    1298
21               REJANE HALUANE CHAVES    1220
22                     WALDIR BERTULIO    1507
23      CASSIA REGINA DE JESUS MARTINS    1099
24               MARCO ANTONIO CAMENAR    1680
25              MARCOS AIRES RODRIGUES    1145
26            RAIMUNDO RODRIGUES FILHO    3500
27                SILVIO NUNES MACHADO    4096
28          BENJAMIM ZANLORENCI JUNIOR    1440
29                DAISY FERREIRA NETTO    1025
...                                ...     ...
7300               LUIS CHAVES DO VALE    9385
7301            LÁZARO BOTELHO MARTINS   41888
7302        MARIA HELENA BRITO MIRANDA    4818
7303           MOISÉS NOGUEIRA AVELINO   33464
7304             OSVALDO DE SOUZA REIS   28227
7305           RAIMUNDO COIMBRA JÚNIOR   69372
7306  ROSA MARIA ARAÚJO DE VASCONCELOS     472
7307           SANSÃO PEREIRA DA SILVA     977
7308               ZULEICA SILVA NEGRI     638
7309           ADALBERTO LEITE BARBOSA    7793
7310          ALEXANDRE SANTIAGO FILHO     304
7311             ANTONIO JORGE GODINHO    4933
7312       CARLOS EDUARDO TORRES GOMES   49455
7313         CONSUELO APARECIDA JULIAO     254
7314            GOIACIARA TAVARES CRUZ   26108
7315             IRAJA SILVESTRE FILHO   39301
7316     JOSEFA ALMEIDA DE SOUSA CUNHA    2555
7317              JOSÉ MAURICIO RABELO    7828
7318           JUAREZ TÁVORA GONÇALVES     795
7319  MARIA AUXILIADORA SEABRA REZENDE   38233
7320  MARIA DE FATIMA SOARES DE ARAUJO     833
7321                NILMAR GAVINO RUIZ   32497
7322            NUBIO GERMANO DA SILVA     192
7323             OTONIEL ANDRADE COSTA   29283
7324          RAIMUNDO MENDES DA SILVA    1302
7325            ROBERTO PEREIRA URBANO    3013
7326    RONALDO DIMAS NOGUEIRA PEREIRA   35980
7327                      SÉRGIO PERIN      20
7328      ÍTALO MARCEL COSTA CONCEIÇÃO     293
7329               LEONAM XAVIER GOMES    1248

[7330 rows x 2 columns]

### Selecionando as colunas nome e votos e apenas as 5 primeiras linhas

In [98]:
data[['nome', 'votos']][:5]

                              nome  votos
0      JOSÉ LUIZ NOGUEIRA DE SOUSA   8579
1                LOIVA DE OLIVEIRA   2757
2  MARIA DALVA DE SOUZA FIGUEIREDO  17428
3                   ROMALDO MILANI   1193
4           ANSELMO DE JESUS ABREU  29401

### Ordenando os dados

In [99]:
data.sort_values(['ano', 'votos'], ascending=False)[:5]

,ano,sequencial_candidato,nome,uf,partido,quantidade_doacoes,quantidade_doadores,total_receita,media_receita,recursos_de_outros_candidatos/comites,...,quantidade_despesas,quantidade_fornecedores,total_despesa,media_despesa,cargo,sexo,grau,estado_civil,ocupacao,votos
6532,2010,250000001352,FRANCISCO EVERARDO OLIVEIRA SILVA,SP,PR,41,32,673383.13,21043.222813,147055.39,...,446,406,623304.57,1535.232931,DEPUTADO FEDERAL,MASCULINO,LÊ E ESCREVE,CASADO(A),ATOR E DIRETOR DE ESPETÁCULOS PÚBLICOS,1353820
5669,2010,190000002498,ANTHONY WILLIAN GAROTINHO MATHEUS DE OLIVEIRA,RJ,PR,236,161,2442612.27,15171.504783,2301824.77,...,368,262,2420839.61,9239.845840,DEPUTADO FEDERAL,MASCULINO,ENSINO MÉDIO COMPLETO,CASADO(A),LOCUTOR E COMENTARISTA DE RÁDIO E TELEVISÃO E ...,694862
6980,2010,250000002829,GABRIEL BENEDITO ISSAAC CHALITA,SP,PSB,124,107,2080738.19,19446.151308,917427.77,...,579,346,1913809.38,5531.240983,DEPUTADO FEDERAL,MASCULINO,SUPERIOR COMPLETO,SOLTEIRO(A),PROFESSOR DE ENSINO SUPERIOR,560022
6716,2010,250000001880,PAULO SALIM MALUF,SP,PP,38,32,668179.00,20880.593750,106947.00,...,369,342,767438.73,2243.972895,DEPUTADO FEDERAL,MASCULINO,SUPERIOR COMPLETO,CASADO(A),EMPRESÁRIO,497203
5915,2010,210000000191,MANUELA PINTO VIEIRA D AVILA,RS,PC do B,404,397,965308.09,2431.506524,298467.40,...,643,546,880585.18,1612.793370,DEPUTADO FEDERAL,FEMININO,SUPERIOR COMPLETO,SOLTEIRO(A),DEPUTADO,482590

### Contando os valores comuns de um atributo

#### Agrupando por sexo

In [100]:
data['sexo'].value_counts()

MASCULINO    6305
FEMININO     1025
Name: sexo, dtype: int64

#### Agrupando por nível de escolaridade

In [101]:
data['grau'].value_counts()

SUPERIOR COMPLETO                4255
ENSINO MÉDIO COMPLETO            1435
SUPERIOR INCOMPLETO               803
ENSINO FUNDAMENTAL COMPLETO       432
ENSINO MÉDIO INCOMPLETO           192
ENSINO FUNDAMENTAL INCOMPLETO     183
LÊ E ESCREVE                       30
Name: grau, dtype: int64

#### Agrupando por partido

In [102]:
data['partido'].value_counts()

PT         606
PMDB       574
PV         526
PDT        503
PSB        485
PSDB       477
PTB        403
PPS        329
PP         323
PSOL       299
PSC        276
PMN        258
PTC        245
PHS        218
PFL        180
PC do B    161
DEM        158
PSL        155
PL         154
PR         138
PT do B    127
PRTB       125
PRB        111
PSDC       109
PRP        107
PTN         91
PRONA       77
PAN         54
PSTU        41
PCB         14
PCO          6
Name: partido, dtype: int64

#### Agrupando por ocupação

In [103]:
data['ocupacao'].value_counts()

OUTROS                                                           819
DEPUTADO                                                         703
ADVOGADO                                                         673
EMPRESÁRIO                                                       629
VEREADOR                                                         326
MÉDICO                                                           325
COMERCIANTE                                                      316
SERVIDOR PÚBLICO ESTADUAL                                        248
SERVIDOR PÚBLICO FEDERAL                                         214
PROFESSOR DE ENSINO MÉDIO                                        172
ADMINISTRADOR                                                    160
ENGENHEIRO                                                       158
APOSENTADO (EXCETO SERVIDOR PÚBLICO)                             153
POLICIAL MILITAR                                                 149
PROFESSOR DE ENSINO SUPERIOR                                     148
SERVIDOR PÚBLICO MUNICIPAL                                       123
ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS                    85
MILITAR REFORMADO                                                 80
ECONOMISTA                                                        76
PROFESSOR DE ENSINO FUNDAMENTAL                                   69
CONTADOR                                                          68
JORNALISTA E REDATOR                                              62
BANCÁRIO E ECONOMIÁRIO                                            56
CORRETOR DE IMÓVEIS, SEGUROS, TÍTULOS E VALORES                   56
SERVIDOR PÚBLICO CIVIL APOSENTADO                                 54
SACERDOTE OU MEMBRO DE ORDEM OU SEITA RELIGIOSA                   51
AGRICULTOR                                                        51
REPRESENTANTE COMERCIAL                                           45
POLICIAL CIVIL                                                    44
ODONTÓLOGO                                                        41
                                                                ...
FISCAL DE TRANSPORTE COLETIVO                                      1
TRABALHADOR DE FABRICAÇÃO DE ROUPAS                                1
ZOOTECNISTA                                                        1
SERVIDOR DA JUSTIÇA ELEITORAL                                      1
TÉCNICO EM EDIFICAÇÕES                                             1
FONOAUDIÓLOGO                                                      1
PROTÉTICO                                                          1
MODELO                                                             1
PREFEITO                                                           1
ALFAIATE E COSTUREIRO                                              1
TABELIÃO                                                           1
ENCANADOR, SOLDADOR, CHAPEADOR E CALDEIREIRO                       1
ARQUEÓLOGO                                                         1
TÉCNICO DE MINERAÇÃO, METALURGIA E GEOLOGIA                        1
ESTIVADOR, CARREGADOR E ASSEMELHADOS                               1
MANICURE E MAQUILADOR                                              1
OPERADOR DE COMPUTADOR                                             1
DEMONSTRADOR                                                       1
CIENTISTA POLÍTICO                                                 1
MESTRE E CONTRAMESTRE DE EMBARCAÇÃO                                1
FÍSICO                                                             1
GARI OU LIXEIRO                                                    1
ESCULTOR E PINTOR                                                  1
CAPITALISTA DE ATIVOS FINANCEIROS                                  1
TRABALHADOR DE FABRICAÇÃO E PREPARAÇÃO DE ALIMENTOS E BEBIDAS      1
TÉCNICO DE BIOLOGIA                                                1
SECURITÁRIO                                                        1
COBRADOR DE TRANSPORTE COLETIVO                                    1
FIANDEIRO, TECELÃO, TINGIDOR E ASSEMELHADOS                        1
FAXINEIRO                                                          1
Name: ocupacao, Length: 175, dtype: int64

#### Agrupando pelo ano da eleição

In [135]:
data['ano'].value_counts()

2010    3942
2006    3388
Name: ano, dtype: int64

## Separando dados das eleições

In [114]:
eleicao_2006 = data[(data.ano==2006)]
eleicao_2010 = data[(data.ano==2010)]

### Agrupando dados de 2006 por partido e sexo

In [152]:
dist_sexo_partido = eleicao_2006.groupby(['partido', 'sexo']).size().reset_index(name="quantidade")
dist_sexo_partido

    partido       sexo  quantidade
0       PAN   FEMININO           4
1       PAN  MASCULINO          50
2   PC do B   FEMININO          15
3   PC do B  MASCULINO          43
4       PCB  MASCULINO           3
5       PCO  MASCULINO           3
6       PDT   FEMININO          28
7       PDT  MASCULINO         248
8       PFL   FEMININO          19
9       PFL  MASCULINO         161
10      PHS   FEMININO          12
11      PHS  MASCULINO          76
12       PL   FEMININO          14
13       PL  MASCULINO         140
14     PMDB   FEMININO          30
15     PMDB  MASCULINO         245
16      PMN   FEMININO          12
17      PMN  MASCULINO          91
18       PP   FEMININO          10
19       PP  MASCULINO         135
20      PPS   FEMININO          23
21      PPS  MASCULINO         185
22      PRB   FEMININO           2
23      PRB  MASCULINO          12
24    PRONA   FEMININO          20
25    PRONA  MASCULINO          57
26      PRP   FEMININO           3
27      PRP  MASCULINO          39
28     PRTB   FEMININO           7
29     PRTB  MASCULINO          34
30      PSB   FEMININO          29
31      PSB  MASCULINO         210
32      PSC   FEMININO          15
33      PSC  MASCULINO         104
34     PSDB   FEMININO          39
35     PSDB  MASCULINO         213
36     PSDC   FEMININO           5
37     PSDC  MASCULINO          58
38      PSL   FEMININO           1
39      PSL  MASCULINO          42
40     PSOL   FEMININO          16
41     PSOL  MASCULINO         104
42     PSTU   FEMININO           4
43     PSTU  MASCULINO          13
44       PT   FEMININO          36
45       PT  MASCULINO         267
46  PT do B  MASCULINO          37
47      PTB   FEMININO          15
48      PTB  MASCULINO         140
49      PTC   FEMININO           8
50      PTC  MASCULINO          47
51      PTN   FEMININO           5
52      PTN  MASCULINO          24
53       PV   FEMININO          30
54       PV  MASCULINO         205

In [154]:
dist_sexo_partido = data.groupby(['ano', 'partido', 'sexo']).size().reset_index(name="quantidade")
dist_sexo_partido.sort_values('partido')

      ano  partido       sexo  quantidade
56   2010      DEM  MASCULINO         146
55   2010      DEM   FEMININO          12
0    2006      PAN   FEMININO           4
1    2006      PAN  MASCULINO          50
2    2006  PC do B   FEMININO          15
3    2006  PC do B  MASCULINO          43
58   2010  PC do B  MASCULINO          81
57   2010  PC do B   FEMININO          22
59   2010      PCB  MASCULINO          11
4    2006      PCB  MASCULINO           3
5    2006      PCO  MASCULINO           3
61   2010      PCO  MASCULINO           2
60   2010      PCO   FEMININO           1
62   2010      PDT   FEMININO          33
63   2010      PDT  MASCULINO         194
6    2006      PDT   FEMININO          28
7    2006      PDT  MASCULINO         248
8    2006      PFL   FEMININO          19
9    2006      PFL  MASCULINO         161
10   2006      PHS   FEMININO          12
11   2006      PHS  MASCULINO          76
64   2010      PHS   FEMININO          16
65   2010      PHS  MASCULINO         114
12   2006       PL   FEMININO          14
13   2006       PL  MASCULINO         140
15   2006     PMDB  MASCULINO         245
14   2006     PMDB   FEMININO          30
66   2010     PMDB   FEMININO          39
67   2010     PMDB  MASCULINO         260
17   2006      PMN  MASCULINO          91
..    ...      ...        ...         ...
93   2010     PSOL  MASCULINO         157
92   2010     PSOL   FEMININO          22
40   2006     PSOL   FEMININO          16
95   2010     PSTU  MASCULINO          18
94   2010     PSTU   FEMININO           6
43   2006     PSTU  MASCULINO          13
42   2006     PSTU   FEMININO           4
97   2010       PT  MASCULINO         254
45   2006       PT  MASCULINO         267
44   2006       PT   FEMININO          36
96   2010       PT   FEMININO          49
98   2010  PT do B   FEMININO          11
99   2010  PT do B  MASCULINO          79
46   2006  PT do B  MASCULINO          37
100  2010      PTB   FEMININO          51
101  2010      PTB  MASCULINO         197
48   2006      PTB  MASCULINO         140
47   2006      PTB   FEMININO          15
103  2010      PTC  MASCULINO         154
102  2010      PTC   FEMININO          36
50   2006      PTC  MASCULINO          47
49   2006      PTC   FEMININO           8
105  2010      PTN  MASCULINO          51
52   2006      PTN  MASCULINO          24
104  2010      PTN   FEMININO          11
51   2006      PTN   FEMININO           5
53   2006       PV   FEMININO          30
106  2010       PV   FEMININO          51
54   2006       PV  MASCULINO         205
107  2010       PV  MASCULINO         240

[108 rows x 4 columns]

In [ ]:
dis