# Brincando com Pandas

In [10]:
%matplotlib inline

import pandas as pd
import matplotlib.pyplot as plt

In [45]:
data = pd.read_csv('/home/lsp/dados/am/eleicoes_2006_a_2010.csv')
data[:3]

,ano,sequencial_candidato,nome,uf,partido,quantidade_doacoes,quantidade_doadores,total_receita,media_receita,recursos_de_outros_candidatos/comites,...,quantidade_despesas,quantidade_fornecedores,total_despesa,media_despesa,cargo,sexo,grau,estado_civil,ocupacao,votos
0,2006,10001,JOSÉ LUIZ NOGUEIRA DE SOUSA,AP,PT,6,6,16600.0,2766.666667,NaN,...,14,14,16583.60,1184.542857,DEPUTADO FEDERAL,MASCULINO,ENSINO MÉDIO COMPLETO,CASADO(A),VEREADOR,8579
1,2006,10002,LOIVA DE OLIVEIRA,RO,PT,13,13,22826.0,1755.846154,6625.0,...,24,23,20325.99,883.738696,DEPUTADO FEDERAL,FEMININO,SUPERIOR COMPLETO,SOLTEIRO(A),SERVIDOR PÚBLICO ESTADUAL,2757
2,2006,10002,MARIA DALVA DE SOUZA FIGUEIREDO,AP,PT,17,16,148120.8,9257.550000,2250.0,...,123,108,146011.70,1351.960185,DEPUTADO FEDERAL,FEMININO,SUPERIOR COMPLETO,VIÚVO(A),PEDAGOGO,17428

É possível configurar a forma de ler um arquivo, como em:

`file = pd.read_csv('file.csv', sep=';', encoding='latin1', parse_dates=['Date'], dayfirst=True, index_col='Date')`

Mudando o separador para **;**
O encoding para **latin1**
E configurando o formato da data

### Pausa para algumas dicas:

Verificando o tipo do objeto e os métodos e atributos disponíveis

In [20]:
type(data)
dir(data)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.

Obter ajuda em um notebook

In [23]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.

Ver a lista de funções mágicas do notebook

In [24]:
%quickref

# Voltando

### Selecionando colunas

In [33]:
data[['nome', 'votos']]

                                  nome   votos
0          JOSÉ LUIZ NOGUEIRA DE SOUSA    8579
1                    LOIVA DE OLIVEIRA    2757
2      MARIA DALVA DE SOUZA FIGUEIREDO   17428
3                       ROMALDO MILANI    1193
4               ANSELMO DE JESUS ABREU   29401
5       JOSÉ RODRIGUES DOS SANTOS NETO    1822
6                  JOSÉ TOMAZ DA SILVA     317
7             LUIZ CARLOS MUNHOZ MEIRA    2591
8                  EDILSON VEIRA ROCHA    2551
9        EDUARDO VALVERDE ARAÚJO ALVES   34631
10                    IRINEU RODRIGUES   26856
11            TARCISIO JOÃO ZIMERMMANN  106659
12               WILLIAN GOMES EUGENIO    1859
13            AMAURI GUEDES DE FREITAS    3752
14                  ELIAS RAMOS SOARES    8346
15       FRANCISCO ALVES DA CRUZ FILHO    4621
16          GILBERTO JOSÉ SPIER VARGAS  124686
17                 GLAYDSTON LIRA GOES     609
18                   ISAAC SILVA GOMES      88
19                 IVETE MARIA RIBEIRO    4959
20         PAULO HENRIQUE COSTA MATTOS    1298
21               REJANE HALUANE CHAVES    1220
22                     WALDIR BERTULIO    1507
23      CASSIA REGINA DE JESUS MARTINS    1099
24               MARCO ANTONIO CAMENAR    1680
25              MARCOS AIRES RODRIGUES    1145
26            RAIMUNDO RODRIGUES FILHO    3500
27                SILVIO NUNES MACHADO    4096
28          BENJAMIM ZANLORENCI JUNIOR    1440
29                DAISY FERREIRA NETTO    1025
...                                ...     ...
7300               LUIS CHAVES DO VALE    9385
7301            LÁZARO BOTELHO MARTINS   41888
7302        MARIA HELENA BRITO MIRANDA    4818
7303           MOISÉS NOGUEIRA AVELINO   33464
7304             OSVALDO DE SOUZA REIS   28227
7305           RAIMUNDO COIMBRA JÚNIOR   69372
7306  ROSA MARIA ARAÚJO DE VASCONCELOS     472
7307           SANSÃO PEREIRA DA SILVA     977
7308               ZULEICA SILVA NEGRI     638
7309           ADALBERTO LEITE BARBOSA    7793
7310          ALEXANDRE SANTIAGO FILHO     304
7311             ANTONIO JORGE GODINHO    4933
7312       CARLOS EDUARDO TORRES GOMES   49455
7313         CONSUELO APARECIDA JULIAO     254
7314            GOIACIARA TAVARES CRUZ   26108
7315             IRAJA SILVESTRE FILHO   39301
7316     JOSEFA ALMEIDA DE SOUSA CUNHA    2555
7317              JOSÉ MAURICIO RABELO    7828
7318           JUAREZ TÁVORA GONÇALVES     795
7319  MARIA AUXILIADORA SEABRA REZENDE   38233
7320  MARIA DE FATIMA SOARES DE ARAUJO     833
7321                NILMAR GAVINO RUIZ   32497
7322            NUBIO GERMANO DA SILVA     192
7323             OTONIEL ANDRADE COSTA   29283
7324          RAIMUNDO MENDES DA SILVA    1302
7325            ROBERTO PEREIRA URBANO    3013
7326    RONALDO DIMAS NOGUEIRA PEREIRA   35980
7327                      SÉRGIO PERIN      20
7328      ÍTALO MARCEL COSTA CONCEIÇÃO     293
7329               LEONAM XAVIER GOMES    1248

[7330 rows x 2 columns]

### Selecionando as colunas nome e votos e apenas as 5 primeiras linhas

In [35]:
data[['nome', 'votos']][:5]

                              nome  votos
0      JOSÉ LUIZ NOGUEIRA DE SOUSA   8579
1                LOIVA DE OLIVEIRA   2757
2  MARIA DALVA DE SOUZA FIGUEIREDO  17428
3                   ROMALDO MILANI   1193
4           ANSELMO DE JESUS ABREU  29401

### Ordenando os dados

In [73]:
data.sort_values(['ano', 'votos'], ascending=False)[:5]

,ano,sequencial_candidato,nome,uf,partido,quantidade_doacoes,quantidade_doadores,total_receita,media_receita,recursos_de_outros_candidatos/comites,...,quantidade_despesas,quantidade_fornecedores,total_despesa,media_despesa,cargo,sexo,grau,estado_civil,ocupacao,votos
6532,2010,250000001352,FRANCISCO EVERARDO OLIVEIRA SILVA,SP,PR,41,32,673383.13,21043.222813,147055.39,...,446,406,623304.57,1535.232931,DEPUTADO FEDERAL,MASCULINO,LÊ E ESCREVE,CASADO(A),ATOR E DIRETOR DE ESPETÁCULOS PÚBLICOS,1353820
5669,2010,190000002498,ANTHONY WILLIAN GAROTINHO MATHEUS DE OLIVEIRA,RJ,PR,236,161,2442612.27,15171.504783,2301824.77,...,368,262,2420839.61,9239.845840,DEPUTADO FEDERAL,MASCULINO,ENSINO MÉDIO COMPLETO,CASADO(A),LOCUTOR E COMENTARISTA DE RÁDIO E TELEVISÃO E ...,694862
6980,2010,250000002829,GABRIEL BENEDITO ISSAAC CHALITA,SP,PSB,124,107,2080738.19,19446.151308,917427.77,...,579,346,1913809.38,5531.240983,DEPUTADO FEDERAL,MASCULINO,SUPERIOR COMPLETO,SOLTEIRO(A),PROFESSOR DE ENSINO SUPERIOR,560022
6716,2010,250000001880,PAULO SALIM MALUF,SP,PP,38,32,668179.00,20880.593750,106947.00,...,369,342,767438.73,2243.972895,DEPUTADO FEDERAL,MASCULINO,SUPERIOR COMPLETO,CASADO(A),EMPRESÁRIO,497203
5915,2010,210000000191,MANUELA PINTO VIEIRA D AVILA,RS,PC do B,404,397,965308.09,2431.506524,298467.40,...,643,546,880585.18,1612.793370,DEPUTADO FEDERAL,FEMININO,SUPERIOR COMPLETO,SOLTEIRO(A),DEPUTADO,482590

### Contando os valores comuns de um atributo

#### Agrupando por sexo

In [46]:
data['sexo'].value_counts()

MASCULINO    6305
FEMININO     1025
Name: sexo, dtype: int64

#### Agrupando por nível de escolaridade

In [48]:
data['grau'].value_counts()

SUPERIOR COMPLETO                4255
ENSINO MÉDIO COMPLETO            1435
SUPERIOR INCOMPLETO               803
ENSINO FUNDAMENTAL COMPLETO       432
ENSINO MÉDIO INCOMPLETO           192
ENSINO FUNDAMENTAL INCOMPLETO     183
LÊ E ESCREVE                       30
Name: grau, dtype: int64

#### Agrupando por partido

In [53]:
data['partido'].value_counts()

PT         606
PMDB       574
PV         526
PDT        503
PSB        485
PSDB       477
PTB        403
PPS        329
PP         323
PSOL       299
PSC        276
PMN        258
PTC        245
PHS        218
PFL        180
PC do B    161
DEM        158
PSL        155
PL         154
PR         138
PT do B    127
PRTB       125
PRB        111
PSDC       109
PRP        107
PTN         91
PRONA       77
PAN         54
PSTU        41
PCB         14
PCO          6
Name: partido, dtype: int64

#### Agrupando por ocupação

In [56]:
data['ocupacao'].value_counts()

OUTROS                                                           819
DEPUTADO                                                         703
ADVOGADO                                                         673
EMPRESÁRIO                                                       629
VEREADOR                                                         326
MÉDICO                                                           325
COMERCIANTE                                                      316
SERVIDOR PÚBLICO ESTADUAL                                        248
SERVIDOR PÚBLICO FEDERAL                                         214
PROFESSOR DE ENSINO MÉDIO                                        172
ADMINISTRADOR                                                    160
ENGENHEIRO                                                       158
APOSENTADO (EXCETO SERVIDOR PÚBLICO)                             153
POLICIAL MILITAR                                                 149
PROFESSOR DE ENSINO SUPERIOR                                     148
SERVIDOR PÚBLICO MUNICIPAL                                       123
ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS                    85
MILITAR REFORMADO                                                 80
ECONOMISTA                                                        76
PROFESSOR DE ENSINO FUNDAMENTAL                                   69
CONTADOR                                                          68
JORNALISTA E REDATOR                                              62
BANCÁRIO E ECONOMIÁRIO                                            56
CORRETOR DE IMÓVEIS, SEGUROS, TÍTULOS E VALORES                   56
SERVIDOR PÚBLICO CIVIL APOSENTADO                                 54
SACERDOTE OU MEMBRO DE ORDEM OU SEITA RELIGIOSA                   51
AGRICULTOR                                                        51
REPRESENTANTE COMERCIAL                                           45
POLICIAL CIVIL                                                    44
ODONTÓLOGO                                                        41
                                                                ...
FISCAL DE TRANSPORTE COLETIVO                                      1
TRABALHADOR DE FABRICAÇÃO DE ROUPAS                                1
ZOOTECNISTA                                                        1
SERVIDOR DA JUSTIÇA ELEITORAL                                      1
TÉCNICO EM EDIFICAÇÕES                                             1
FONOAUDIÓLOGO                                                      1
PROTÉTICO                                                          1
MODELO                                                             1
PREFEITO                                                           1
ALFAIATE E COSTUREIRO                                              1
TABELIÃO                                                           1
ENCANADOR, SOLDADOR, CHAPEADOR E CALDEIREIRO                       1
ARQUEÓLOGO                                                         1
TÉCNICO DE MINERAÇÃO, METALURGIA E GEOLOGIA                        1
ESTIVADOR, CARREGADOR E ASSEMELHADOS                               1
MANICURE E MAQUILADOR                                              1
OPERADOR DE COMPUTADOR                                             1
DEMONSTRADOR                                                       1
CIENTISTA POLÍTICO                                                 1
MESTRE E CONTRAMESTRE DE EMBARCAÇÃO                                1
FÍSICO                                                             1
GARI OU LIXEIRO                                                    1
ESCULTOR E PINTOR                                                  1
CAPITALISTA DE ATIVOS FINANCEIROS                                  1
TRABALHADOR DE FABRICAÇÃO E PREPARAÇÃO DE ALIMENTOS E BEBIDAS      1
TÉCNICO DE BIOLOGIA                                                1
SECURITÁRIO                                                        1
COBRADOR DE TRANSPORTE COLETIVO                                    1
FIANDEIRO, TECELÃO, TINGIDOR E ASSEMELHADOS                        1
FAXINEIRO                                                          1
Name: ocupacao, Length: 175, dtype: int64

#### Agrupando pelo ano da eleição

In [62]:
data['ano'].value_counts()

2010    3942
2006    3388
Name: ano, dtype: int64